// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://caamvaqelopbpaavesqk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNhYW12YXFlbG9wYnBhYXZlc3FrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3ODM2MDEsImV4cCI6MjA3MjM1OTYwMX0.zMEnNxC21zGZ696C4OVjV4f3vjAKCXoMnInVNLv77w0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});